name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      deployments: write

    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: JDK v21 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: gradlew 실행권한 부여
        run: chmod +x gradlew

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build

      - name: Docker hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: DockerHub에 빌드 및 배포
        env:
          NAME: ${{ secrets.DOCKERHUB_USERNAME }}
          REPO: email-test
        run: |
          docker build -t $REPO .
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push $NAME/$REPO:latest

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            mkdir -p /home/ec2-user/app
            chown ec2-user:ec2-user /home/ec2-user/app
            
            wget -O docker-compose.yml https://raw.githubusercontent.com/Ryan-Dia/email-test/main/docker-compose.yml
            
            # docker-compose 명령 실행
            docker compose down || true  
            docker compose pull
            docker compose up -d
